server:
  port: 8080
  servlet:
    context-path: /migration
spring:
  datasource:
        url: jdbc:mysql://172.31.140.232:4001/bme_prod?characterEncoding=utf-8&useSSL=false&autoReconnect=true
        username: root
        password: bme@123
        driver-class-name: com.mysql.cj.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
mybatis-plus:
  # 如果是放在resource目录 classpath:/mapping/*Mapper.xml
  mapper-locations: classpath:/mapping/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: zyun.bme.platform.sys.models
  global-config:
    id-type: 2
    field-strategy: 0
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #自定义填充策略接口实现
    # meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
    call-setters-on-nulls: true